### ISSUE TITLE
ORA-6502 when trying to return clob from the stored procedure

### ISSUE THREAD

**Issue by psylone** [erlangbureau/jamdb_oracle#119]
Hi guys and thanks for all your amazing work!

I have a big trouble when trying to return a large character data from the stored procedure. Here's example:

```elixir
sql = """
DECLARE
  a clob := '#{String.duplicate("*", 4001)}';
BEGIN
  :1 := a;
END;
"""

MyApp.Repo.query(sql, [out: :clob])
```

This will work if I replace `4001` with `4000`. Can you please help with this? Thought `[out: :clob]` should work but seems it doesn't and `varchar` is using in `out` instead.

Thanks!

**Comment by vstavskyi** [comment]
max data length [fix](https://github.com/erlangbureau/jamdb_oracle/commit/63859fde286cc2135bc03963b546f3190f424d1b)

**Comment by psylone** [comment]
> max data length [fix](https://github.com/erlangbureau/jamdb_oracle/commit/63859fde286cc2135bc03963b546f3190f424d1b)

Thanks for the rapid action!

Tested, it seems to work. Are you plan to release a patched version on hex.pm?

Also do you interested to bring some sort of CI in the project?

**Comment by vstavskyi** [comment]
I am running mix test and rebar3 ct manually. 
But if you'll make a pull request with CI configuration, I'll definitely merge it.
Publishing to hex will be at the usual time next month.
If you have any driver patch, please pull it and it'll be included in the next publishing :)

**Comment by NikitaNaumenko** [comment]
Hello, thanks for your work, max length helps, but if data greater than 35k, it doesn't work.
Thanks!

**Comment by vstavskyi** [comment]
@psylone 
Create elixir.yml
https://github.com/erlangbureau/jamdb_oracle/actions

**Comment by NikitaNaumenko** [comment]
I fetched latest version from master, and now I get this error
`"'ORA-06502: PL/SQL: numeric or value error\\nORA-06512: at line 7\\n'"`

**Comment by psylone** [comment]
> @psylone Create elixir.yml https://github.com/erlangbureau/jamdb_oracle/actions

Yeah, sorry for the delay, will do it this week.

**Comment by vstavskyi** [comment]
The problem with empty error message was fixed.
Maybe not completly, but still.

**Comment by vstavskyi** [comment]
> max data length [fix](https://github.com/erlangbureau/jamdb_oracle/commit/63859fde286cc2135bc03963b546f3190f424d1b)

This fix caused problems
[revert](https://github.com/erlangbureau/jamdb_oracle/commit/051783af65d3571c463fa4b633b40a084be281ad)

**Comment by NikitaNaumenko** [comment]
I'm not sure) because now I get
`"'ORA-06502: PL/SQL: numeric or value error: character string buffer too small\\nORA-06512: at line 7\\n'",`
before, it works perfect

**Comment by vstavskyi** [comment]
new [fix](https://github.com/erlangbureau/jamdb_oracle/commit/d04aea2efb07d3525583f0f2de3ae79776c0b85e)

**Comment by NikitaNaumenko** [comment]
Thanks,  but still the same error
`{:error,
 %DBConnection.ConnectionError{
   message: "'ORA-06502: PL/SQL: numeric or value error\\nORA-06512: at line 7\\n'",
   severity: :error,
   reason: :error
 }}`
 Maybe it helps you, but when we use DBMS_OUTPUT.PUT_LINE(result) we got same error, if we just call procedure, it finishes successfully and we can get the result from log table (procedure write results  of procedures to table)

**Comment by vstavskyi** [comment]
max length 33554432 or 32k has not changed
